api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/DTO']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    error_formats:
        json:
            mime_types: ['application/json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header